### ISSUE TITLE
Parameters order

### ISSUE THREAD

**Issue by ainthek** [tonthanhhung/string-template-extractor#2]
swap params to allow easier bind()

intended usage:

var template=require("string-template-extractor")
	.bind(null,"${user}/${password}@{connectString}");

module.exports = function() {
    return template.parse(process.env.db_connection_str);
}

**Comment by tonthanhhung** [comment]
Fixed
the parameters iorder now changed with template comes first
add helper function for create template, see README
@ainthek :+1: for binding function remind, your sample template is missing "$" at "{connectString}". I implemented to return Error when template mismatch.
The version now is 2.0.2 due to not backward compatible.
